### ISSUE TITLE
Gerrit version to use ?

### ISSUE THREAD

**Issue by jeeloo** [GerritForge/gerrit-virtualhost#1]
Hi
I would like to try this "plugin" but I'm having problems finding a suitable Gerrit version to get it working. If I try latests or the latest tag it doesn't compile and now I have moved back to v2.14.2-2566-gd32409d823 in the gerrit repo and both Gerrit and virtualhost compiles but then I get errors in runtime which does not seem to be related to virtualhost. So is there a Gerrit version or commit which is known to work together with virtualhost?

**Comment by lucamilanesio** [comment]
@jeeloo can you post your issue on the [Gerrit Mailing List](https://groups.google.com/forum/#!forum/repo-discuss)? I would be more than happy to answer you over there.
